name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        jdk-version: [8, 11, 17]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: temurin
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test
      - name: Process Errors
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Gradle test (Java ${{matrix.jdk-version}})
          path: build/test-results/test/*.xml
          reporter: java-junit
